In [3]:
import numpy as np

## Create array

In [2]:
a=np.array([1,2,3,4,5],dtype='f') #numpy List
b=np.array((3,4,65,7,7)) #numpy tuple

In [3]:
print(a)
print(b)

[1. 2. 3. 4. 5.]
[ 3  4 65  7  7]


In [4]:
print(a.dtype)

float32


In [5]:
print(b.dtype)

int32


## Different ways to Creating array with random numbers

### Normal

In [5]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

### arange(start,end(excluded),increament/decreament)   

In [8]:
b=np.arange(50) 
# Here, start->default-0
# increment = 1
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
c=np.arange(20,50,4)   #start=20 end=50(excluded) increment=4
c

array([20, 24, 28, 32, 36, 40, 44, 48])

### with Random

In [10]:
d=np.random.permutation(np.arange(10))
d

array([8, 0, 1, 7, 5, 6, 2, 4, 3, 9])

In [16]:
e =np.random.rand(2,3)
e   # this will create float type array and max. elemens near zero
# so next way is better -->below

array([[0.6465783 , 0.00616545, 0.85581743],
       [0.24251628, 0.10556092, 0.24564573]])

In [17]:
f =np.round(10*np.random.rand(5,4))
f

array([[ 1.,  3.,  7.,  5.],
       [ 5.,  8.,  3.,  2.],
       [ 9.,  1.,  3., 10.],
       [ 4.,  2.,  7.,  4.],
       [ 0.,  8.,  6.,  8.]])

### random -> int array 

In [19]:
Array=np.random.randint(10,size=5)
Array

array([7, 4, 9, 5, 9])

In [20]:
Ar=np.random.randint(20,size=(3,3))
Ar

array([[ 3,  2,  5],
       [ 2,  0, 17],
       [10,  2, 13]])

### with arange and reshape

In [11]:
e=np.arange(10).reshape(5,2)
e

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## End for Array

# Functions: 

<h2>ndim-->n Dimention</h2>

In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)

2


In [7]:
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b.ndim)

3


<h3>Accessing 2D array </h3>

In [8]:
#Directly accessing the 2D Array Example: 'a'
print(a[0,2])
print(a[1,0])

3
4


<h3>3-D array means combine 2 2-D Arrays</h3>

In [9]:
#lets access 8 from b
b[1,0,1]
# first move to that 2d array, then move to that 1-d array then 
#move to that element.

8

<h3>Shape,Size<h3>

In [10]:
print(b.shape)
#here 2 is no. of 2D array in b
#another 2 is no. of 1D array ib b
#last 3 is the no. of elements that 1d array have
print(b.shape[0],b.shape[1],b.shape[2])

(2, 2, 3)
2 2 3


In [11]:
for x in a:
    for y in x:
        print(y,"\t" ,end=" ")

1 	 2 	 3 	 4 	 5 	 6 	 7 	 8 	 9 	 

In [12]:
#total no. of elements
b.size

12

In [13]:
#arange generates a array for us within a small time
#similar, to range function
A=np.arange(50)
B=np.arange(20,50)
C=np.arange(20,50,4)

In [14]:
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [15]:
print(B)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [16]:
print(C)

[20 24 28 32 36 40 44 48]


<h2>Random </h2>

In [17]:
#np.arange will give us an array from 0-9
#and random.permutation will shuffle all elements to give New Array
A=np.random.permutation(np.arange(10))
A

array([3, 2, 4, 7, 0, 8, 1, 9, 5, 6])

### for single random number

In [18]:
#for single random number
B=np.random.randint(10,20)
B

19

In [19]:
# to create a random array of 2D(here 2-rows 3-colums)
C=np.random.rand(2,3)
print(C)
print(C.ndim)
C.shape

[[0.74452463 0.29661085 0.38490383]
 [0.26905403 0.70467316 0.11270699]]
2


(2, 3)

In [20]:
#arange will generate Array and Reshape will give Dimentions to it.
D=np.arange(10).reshape(5,2)
print("Dimention:-",D.ndim)
print(D)
D.shape

Dimention:- 2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


(5, 2)

In [21]:
#creating 3D array
E=np.arange(100).reshape(4,5,5)
print(E.shape)
print(E)

(4, 5, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

# Slicing In Numpy

In [24]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
brr=arr[3:15]
brr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
#here changing an element of sliced array will also affect our main array....
#So Sliced array is a reference to main array.
#that's the main difference between sliced numpy array and normal list array
brr[1]=25
print(brr)
print(arr)

[ 3 25  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 25  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
#if above type not wanted then:--
crr=arr[10:16].copy()
print(crr)
crr[1]=55
print(crr)
print(arr)

[10 11 12 13 14 15]
[10 55 12 13 14 15]
[ 0  1  2  3 25  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [28]:
arr[4]=4 #turning array back to normal
arr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
#reverse array
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [30]:
np.index_exp??

In [31]:
#finding index of array
idx = np.argwhere(arr==5)[0][0]
idx

5

In [32]:
Ar=np.round(10*np.random.rand(5,4))
Ar

array([[ 5.,  5.,  5.,  3.],
       [10.,  9.,  1.,  8.],
       [ 6.,  4.,  5.,  6.],
       [10.,  1.,  5.,  0.],
       [ 9.,  2.,  3.,  3.]])

In [33]:
Ar[1,3]

8.0

# Slicing 2D array

In [34]:
#row 1 and all column
#a[row,column]
Ar[1,:]

array([10.,  9.,  1.,  8.])

In [36]:
# column 1 and all rows
Ar[:,1]

array([5., 9., 4., 1., 2.])

In [37]:
Ar[1:3,2:4]

array([[1., 8.],
       [5., 6.]])

In [38]:
Ar.T

array([[ 5., 10.,  6., 10.,  9.],
       [ 5.,  9.,  4.,  1.,  2.],
       [ 5.,  1.,  5.,  5.,  3.],
       [ 3.,  8.,  6.,  0.,  3.]])

# Sort multidimentional ArraY(Rowwise,ColumnWise)

In [ ]:
#Row=> axis=1
#Column=> axis=0

In [43]:
#Row
Ar.sort(axis=0)
Ar

array([[ 5.,  1.,  1.,  0.],
       [ 6.,  2.,  3.,  3.],
       [ 9.,  4.,  5.,  3.],
       [10.,  5.,  5.,  6.],
       [10.,  9.,  5.,  8.]])

In [45]:
#Column
Ar.sort(axis=1)
Ar

array([[ 0.,  1.,  1.,  5.],
       [ 2.,  3.,  3.,  6.],
       [ 3.,  4.,  5.,  9.],
       [ 5.,  5.,  6., 10.],
       [ 5.,  8.,  9., 10.]])

# Linear Algebra Library in Numpy

In [39]:
import numpy.linalg as la

In [40]:
la.inv(np.random.rand(3,3))

array([[ 10.33728398,  34.23326291, -38.95103269],
       [ -1.28571313,  -8.92858991,  10.15243887],
       [ -4.23435773,  -9.35346612,  11.93797741]])

# Numpy Slicing by Indexing Also called Masking

In [86]:
#another way to generate array
Array=np.random.randint(10,size=10)
Array

array([8, 9, 5, 9, 5, 5, 5, 0, 3, 1])

In [92]:
#1. Passing Index
Brray=Array[[3,5,6]]
Brray

array([9, 5, 5])

In [93]:
#but there a change in comparison to Numpy Slicing 
#changing value does not affect real one...

In [96]:
Brray[0]=11
print(Brray)
print(Array)

[11  5  5]
[8 9 5 9 5 5 5 0 3 1]


In [99]:
#2. Passing condition
Crray=Array[Array>6]
Crray

array([8, 9, 9])

In [105]:
Drray=Array[(Array>4) & (Array<9)]
Drray

array([8, 5, 5, 5, 5])

In [106]:
#used for Array and gives Value,,,,,used for normal and gives True/False
#&  ,,,, and 
# |  ,,, or
# ~   ,,, not

# BroadCasting 

In [113]:
Ar=np.random.randint(20,size=(3,3))
Ar

array([[ 5,  8,  5],
       [13,  1,  7],
       [ 5, 14, 11]])

In [114]:
Ar=Ar+5
Ar

array([[10, 13, 10],
       [18,  6, 12],
       [10, 19, 16]])

# Universal functions 

In [115]:
# np.hstack (Horizontal Stack)
# np.vstack (vertical Stack)
# np.sort 

In [14]:
A=np.round(20*np.random.rand(3,4))
A

array([[ 7., 19., 12., 17.],
       [16., 11.,  9.,  5.],
       [ 1., 18.,  3., 13.]])

In [15]:
B=np.random.randint(20,size=(3,4))
B

array([[ 4,  9, 10, 13],
       [ 0,  9,  6, 15],
       [10, 11, 15,  9]])

<h2><b>hstack--></b> combines 2 arrays in horizontal order</h2>

In [16]:
C=np.hstack((A,B))
C

array([[ 7., 19., 12., 17.,  4.,  9., 10., 13.],
       [16., 11.,  9.,  5.,  0.,  9.,  6., 15.],
       [ 1., 18.,  3., 13., 10., 11., 15.,  9.]])

<h2>vstack--> combines 2 arrays in horizontal order</h2>

In [17]:
D=np.vstack((A,B))
D

array([[ 7., 19., 12., 17.],
       [16., 11.,  9.,  5.],
       [ 1., 18.,  3., 13.],
       [ 4.,  9., 10., 13.],
       [ 0.,  9.,  6., 15.],
       [10., 11., 15.,  9.]])

<h2>sort with axis 0(column) and axis 1(row)</h2>

In [26]:
E=np.sort(C,axis=0)
E

array([[ 1., 11.,  3.,  5.,  0.,  9.,  6.,  9.],
       [ 7., 18.,  9., 13.,  4.,  9., 10., 13.],
       [16., 19., 12., 17., 10., 11., 15., 15.]])

In [27]:
F=np.sort(D,axis=1)
F

array([[ 7., 12., 17., 19.],
       [ 5.,  9., 11., 16.],
       [ 1.,  3., 13., 18.],
       [ 4.,  9., 10., 13.],
       [ 0.,  6.,  9., 15.],
       [ 9., 10., 11., 15.]])

# Reverse

In [38]:
E[::-1,:]

array([[16., 19., 12., 17., 10., 11., 15., 15.],
       [ 7., 18.,  9., 13.,  4.,  9., 10., 13.],
       [ 1., 11.,  3.,  5.,  0.,  9.,  6.,  9.]])

In [41]:
F[:,::-1]

array([[19., 17., 12.,  7.],
       [16., 11.,  9.,  5.],
       [18., 13.,  3.,  1.],
       [13., 10.,  9.,  4.],
       [15.,  9.,  6.,  0.],
       [15., 11., 10.,  9.]])

# End